name: gnn
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.121
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cudatoolkit=11.7.0
  - freetype=2.12.1
  - intel-openmp=2024.0.0
  - jpeg=9b
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.19
  - libffi=3.4.4
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.43
  - libsqlite=3.45.2
  - libtiff=4.5.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.12.5
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - msys2-conda-epoch=20160418
  - numpy=1.24.4
  - openssl=3.2.1
  - pip=22.3.1
  - pthreads-win32=2.9.1
  - python=3.8.13
  - python_abi=3.8
  - setuptools=69.2.0
  - sqlite=3.45.2
  - tbb=2021.11.0
  - tk=8.6.13
  - typing_extensions=4.10.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.42.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - docker-pycreds==0.4.0
      - ftfy==6.1.3
      - gitdb==4.0.11
      - gitpython==3.1.42
      - idna==3.6
      - imageio-ffmpeg==0.4.3
      - lpips==0.1.4
      - ninja==1.11.1.1
      - pathtools==0.1.2
      - pillow==9.0.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyspng==0.1.1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - scipy==1.10.1
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - torch==1.7.1+cu110
      - torchvision==0.8.2+cu110
      - tqdm==4.66.2
      - urllib3==2.2.1
      - wandb==0.13.9
      - wcwidth==0.2.13
